### ISSUE TITLE
Error when pressing F12

### ISSUE THREAD

**Issue by skaa** [SLaks/Ref12#25]
Visual Studio 2015 Update 1, Ref12 4.2.1. Getting error in output window:
```
Ref12: Errors occurred while trying all reference URLs; Ref12 will not work
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Remove(Int32 startIndex)
   at SLaks.Ref12.Services.ReferenceSourceProvider.<>c.<LookupService>b__9_1(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at SLaks.Ref12.Services.ReferenceSourceProvider.<LookupService>d__9.MoveNext()
```

**Comment by SLaks** [comment]
This happens if you have a proxy blocking connectivity to the Reference Source server.
