### ISSUE TITLE
Ref12 fails to load reference URL

### ISSUE THREAD

**Issue by angelobreuer** [SLaks/Ref12#38]
I get the following exception when starting up Visual Studio:
```
08.01.2021 16:40:11: Ref12: Errors occurred while trying all reference URLs; Ref12 will not work
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'roslynsourceindex.azurewebsites.net'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SLaks.Ref12.Services.ReferenceSourceProvider.<LookupService>d__9.MoveNext()
08.01.2021 16:40:12: Ref12: Using reference source from https://referencesource.microsoft.com with 114 assemblies
```

I am using Microsoft Visual Studio Community 2019, Version 16.8.3, with a .NET Core project.

**Comment by nam20485** [comment]
I get the same exact message. Any idea how to fix? 

Visual Studio Professional 2019 v16.11.7 in a .NET Core project.

http://roslynsourceindex.azurewebsites.net does indeed not resolve when I try it in a web browser.

What is this URL?
